<?php

 $apiKey = "rzp_test_VDfNumPM1IABiY";
 session_start();
 $amount = $_SESSION['amount'];
 $flatowner = $_SESSION['flatowner'];
 $contact = $_SESSION['contact'];
 $email = $_SESSION['email'];
?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="../confirmpayment.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amount*100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="EasySociety"
    data-description="Maintenance Bill Payment!"
    data-image="../EasySociety/images/maintenance.jpg"
    data-prefill.name="<?php echo $flatowner;?>"
    data-prefill.email="<?php echo $email;?>"
    data-prefill.contact="<?php echo $contact;?>"
    data-theme.color="#F37254"
	data-buttontext.margin = "50%"
></script>
<input type="hidden" custom="Hidden Element" name="hidden" style="text-align:center">
</form>

